camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All

spring.datasource:
  url: jdbc:h2:mem:testdb
  username: camunda
  password: camunda
  driver-class-name: org.h2.Driver


server:
  port: 48080
